{
 "title": "Process \"Top\"",
 "description": "Mimic \"top\" Linux command - view processes and their system resource usage. Datasource: InfluxDB; Collector: Telegraf",
 "tags": [
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   },
   {
    "name": "inter",
    "label": "Interval",
    "query": "1s,5s,10s,30s,1m,2m,5m,10m,30m,1h,1d"
   }
  ]
 },
 "panels": [
  { "title": "SYSTEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process \"Top\" CPU, % от одного ядра",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_process_name",
     "measurement": "procstat",
     "query": "SELECT cpu_usage  FROM \"procstat\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY process_name",
     "select": [
      [
       { "params": [ "memory_vms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process \"Top\" RAM, % total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_process_name",
     "measurement": "procstat",
     "query": "SELECT memory_usage FROM \"procstat\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY process_name",
     "select": [
      [
       { "params": [ "memory_vms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process \"Top\" read bytes, bytes/second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_process_name",
     "measurement": "procstat",
     "query": "SELECT non_negative_derivative(mean(read_bytes), 1s) FROM \"procstat\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY process_name, time($interval)",
     "select": [
      [
       { "params": [ "memory_vms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Process \"Top\" write bytes, bytes/second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_process_name",
     "measurement": "procstat",
     "query": "SELECT non_negative_derivative(mean(write_bytes), 1s) FROM \"procstat\" WHERE \"host\" =~ /$server$/ AND $timeFilter GROUP BY process_name, time($interval)",
     "select": [
      [
       { "params": [ "memory_vms" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}