{
 "title": "Программные метрики",
 "time": { "from": "2021-06-17T01:25:54.000Z", "to": "2021-06-17T03:07:10.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Число событий с группировкой по типу",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_timestampKind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "timestampKind" ], "type": "tag" }
     ],
     "measurement": "timestamps",
     "select": [
      [
       { "params": [ "client" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "timestampKind", "operator": "=~", "value": "/^[CSP].*/" }
     ]
    }
   ]
  },
  {
   "title": "Сводная таблица основных интервалов между тиместампами, миллисекунды",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "Stats",
     "groupBy": [
      { "params": [ "timestampKind" ], "type": "tag" }
     ],
     "measurement": "timestamps",
     "query": "SELECT count(\"value\"),mean(\"value\"),percentile(\"value\", 95) as \"95th percentile\",max(\"value\") ,  min(\"value\"), stddev(\"value\") , pow(stddev(\"value\"),2) as dispersion FROM \"timestamps\" WHERE $timeFilter GROUP BY \"timestampKind\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Длительность цепочки от вызова API клиентом до возврата принятого конверта клиенту(C01-C15) средняя",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "timestamps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "timestampKind", "operator": "=", "value": "P01" }
     ]
    }
   ]
  },
  {
   "title": "Длительность цепочки от запроса на публикацию серверу до загрузки данных нотификаций из redis(S03-S09)  средняя",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "timestamps",
     "query": "SELECT count(\"value\") FROM \"timestamps\" WHERE (\"timestampKind\" = 'S03' OR \"timestampKind\" = 'S09') AND $timeFilter GROUP BY time($__interval), \"envelope\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "timestampKind", "operator": "=", "value": "P02" }
     ]
    }
   ]
  },
  {
   "title": "Длительность цепочки от загрузки данных нотификаций из redis до возврата принятого конверта клиенту(S09-C15)  средняя",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "timestamps",
     "query": "SELECT count(\"value\") FROM \"timestamps\" WHERE (\"timestampKind\" = 'S09' OR \"timestampKind\" = 'C15') AND $timeFilter GROUP BY time($__interval), \"envelope\", \"client\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "timestampKind", "operator": "=", "value": "P03" }
     ]
    }
   ]
  },
  {
   "title": "Длительности D** средние",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_timestampKind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "timestampKind" ], "type": "tag" }
     ],
     "measurement": "timestamps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "timestampKind", "operator": "=~", "value": "/^D/" }
     ]
    }
   ]
  },
  {
   "title": "Длительности D** максимальные",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_timestampKind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "timestampKind" ], "type": "tag" }
     ],
     "measurement": "timestamps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "timestampKind", "operator": "=~", "value": "/^D/" }
     ]
    }
   ]
  },
  {
   "title": "Длительности P** средние",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_timestampKind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "timestampKind" ], "type": "tag" }
     ],
     "measurement": "timestamps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "timestampKind", "operator": "=~", "value": "/^P/" }
     ]
    }
   ]
  },
  {
   "title": "Длительности P** максимальные",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_timestampKind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "timestampKind" ], "type": "tag" }
     ],
     "measurement": "timestamps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "timestampKind", "operator": "=~", "value": "/^P/" }
     ]
    }
   ]
  },
  {
   "title": "Статус основных компонентов объекта тестирования",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_container",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "health",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Файлов в папке /out нативного клиента, отправляющего файлы",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "application",
     "select": [
      [
       { "params": [ "client_files" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}